import type { EnemyConfig } from '../types';

export const ENEMIES: EnemyConfig[] = [
  {
    id: 'slime',
    name: 'Slime',
    spriteAtlas: '/assets/enemies/slime.png',
    animations: {
      idle: { frames: [0], frameRate: 0, loop: true },
      walk: { frames: [0, 1, 2, 3], frameRate: 6, loop: true },
    },
    hp: 20,
    speed: 1.5,
    damage: 5,
    attackRange: 0.5,
    attackSpeed: 1,
    goldDrop: 1,
    xpDrop: 5,
    scale: 0.8,
  },
  {
    id: 'goblin',
    name: 'Goblin',
    spriteAtlas: '/assets/enemies/goblin.png',
    animations: {
      idle: { frames: [0], frameRate: 0, loop: true },
      walk: { frames: [0, 1, 2, 3], frameRate: 8, loop: true },
    },
    hp: 40,
    speed: 2,
    damage: 8,
    attackRange: 0.5,
    attackSpeed: 1.2,
    goldDrop: 2,
    xpDrop: 10,
    scale: 1,
  },
  {
    id: 'orc',
    name: 'Orc',
    spriteAtlas: '/assets/enemies/orc.png',
    animations: {
      idle: { frames: [0], frameRate: 0, loop: true },
      walk: { frames: [0, 1, 2, 3], frameRate: 6, loop: true },
    },
    hp: 80,
    speed: 1.2,
    damage: 15,
    attackRange: 0.6,
    attackSpeed: 0.8,
    goldDrop: 5,
    xpDrop: 20,
    scale: 1.3,
  },
  {
    id: 'demon',
    name: 'Demon',
    spriteAtlas: '/assets/enemies/demon.png',
    animations: {
      idle: { frames: [0], frameRate: 0, loop: true },
      walk: { frames: [0, 1, 2, 3], frameRate: 8, loop: true },
    },
    hp: 150,
    speed: 2.5,
    damage: 25,
    attackRange: 0.7,
    attackSpeed: 1.5,
    goldDrop: 10,
    xpDrop: 50,
    scale: 1.5,
  },
];
