import type { WeaponConfig } from '../types';

export const WEAPONS: WeaponConfig[] = [
  {
    id: 'stick',
    name: 'Stick',
    description: 'A simple wooden stick',
    icon: '/assets/weapons/stick.png',
    damage: 10,
    attackSpeed: 1,
    range: 4,
    projectileSpeed: 8,
    piercing: 0,
    projectileSprite: '/assets/weapons/stick_projectile.png',
    projectileScale: 0.3,
  },
  {
    id: 'sword',
    name: 'Sword',
    description: 'A basic sword with decent damage',
    icon: '/assets/weapons/sword.png',
    damage: 15,
    attackSpeed: 1.2,
    range: 5,
    projectileSpeed: 10,
    piercing: 0,
    projectileSprite: '/assets/weapons/sword_projectile.png',
    projectileScale: 0.4,
  },
  {
    id: 'bow',
    name: 'Bow',
    description: 'Long range weapon with fast projectiles',
    icon: '/assets/weapons/bow.png',
    damage: 12,
    attackSpeed: 0.8,
    range: 8,
    projectileSpeed: 15,
    piercing: 1,
    projectileSprite: '/assets/weapons/arrow.png',
    projectileScale: 0.3,
  },
  {
    id: 'magic_staff',
    name: 'Magic Staff',
    description: 'Shoots magic projectiles that pierce enemies',
    icon: '/assets/weapons/staff.png',
    damage: 20,
    attackSpeed: 0.6,
    range: 7,
    projectileSpeed: 12,
    piercing: 3,
    projectileSprite: '/assets/weapons/magic_projectile.png',
    projectileScale: 0.5,
  },
  {
    id: 'axe',
    name: 'Axe',
    description: 'Slow but powerful weapon',
    icon: '/assets/weapons/axe.png',
    damage: 30,
    attackSpeed: 0.5,
    range: 4.5,
    projectileSpeed: 9,
    piercing: 0,
    projectileSprite: '/assets/weapons/axe_projectile.png',
    projectileScale: 0.5,
  },
];
