import type { LevelConfig, LevelGroupConfig } from './types';

export interface AudioConfig {
  music: string;
  volume: number;
  loop: boolean;
}

export const AUDIO_TRACKS: Record<string, AudioConfig> = {
  track1: {
    music: '/assets/audio/music-calm.mp3',
    volume: 0.5,
    loop: true,
  },
  track2: {
    music: '/assets/audio/music-upbeat.mp3',
    volume: 0.5,
    loop: true,
  },
  track3: {
    music: '/assets/audio/music-intense.mp3',
    volume: 0.5,
    loop: true,
  },
};

export const SOUND_EFFECTS = {
  draw: '/assets/audio/sfx-draw.mp3',
  erase: '/assets/audio/sfx-erase.mp3',
  goal: '/assets/audio/sfx-goal.mp3',
  fail: '/assets/audio/sfx-fail.mp3',
  click: '/assets/audio/sfx-click.mp3',
};

export const LEVEL_GROUPS: LevelGroupConfig[] = [
  { name: 'Tutorial', color: '#4CAF50', unlockLevel: 0 },
  { name: 'Easy', color: '#2196F3', unlockLevel: 3 },
  { name: 'Medium', color: '#FF9800', unlockLevel: 8 },
  { name: 'Hard', color: '#F44336', unlockLevel: 15 },
];

export const LEVELS: LevelConfig[] = [
  // Tutorial Group (0-2)
  {
    name: 'Level 1',
    groupIndex: 0,
    ballStart: { x: -3, y: 2 },
    goalPosition: { x: 3, y: 2 },
    obstacles: [],
    maxPathLength: 100,
    musicTrack: 'track1',
    backgroundColor: '#87CEEB',
    difficulty: 'easy',
  },
  {
    name: 'Level 2',
    groupIndex: 0,
    ballStart: { x: -3, y: 2 },
    goalPosition: { x: 3, y: -2 },
    obstacles: [
      { type: 'box', x: 0, y: 0, width: 1, height: 1 },
    ],
    maxPathLength: 120,
    musicTrack: 'track1',
    backgroundColor: '#87CEEB',
    difficulty: 'easy',
  },
  {
    name: 'Level 3',
    groupIndex: 0,
    ballStart: { x: -3, y: 3 },
    goalPosition: { x: 3, y: -3 },
    obstacles: [
      { type: 'box', x: -1, y: 1, width: 1, height: 1 },
      { type: 'box', x: 1, y: -1, width: 1, height: 1 },
    ],
    maxPathLength: 150,
    musicTrack: 'track1',
    backgroundColor: '#87CEEB',
    difficulty: 'easy',
  },

  // Easy Group (3-7)
  {
    name: 'Level 4',
    groupIndex: 1,
    ballStart: { x: -4, y: 0 },
    goalPosition: { x: 4, y: 0 },
    obstacles: [
      { type: 'box', x: -2, y: 0, width: 0.8, height: 2 },
      { type: 'box', x: 2, y: 0, width: 0.8, height: 2 },
    ],
    maxPathLength: 180,
    musicTrack: 'track2',
    backgroundColor: '#90EE90',
    difficulty: 'easy',
  },
  {
    name: 'Level 5',
    groupIndex: 1,
    ballStart: { x: -3, y: 3 },
    goalPosition: { x: 3, y: 3 },
    obstacles: [
      { type: 'box', x: 0, y: 2, width: 3, height: 0.5 },
      { type: 'box', x: -1.5, y: 0, width: 0.5, height: 2 },
      { type: 'box', x: 1.5, y: 0, width: 0.5, height: 2 },
    ],
    maxPathLength: 200,
    musicTrack: 'track2',
    backgroundColor: '#90EE90',
    difficulty: 'easy',
  },
  {
    name: 'Level 6',
    groupIndex: 1,
    ballStart: { x: -3, y: -3 },
    goalPosition: { x: 3, y: 3 },
    obstacles: [
      { type: 'box', x: -1, y: -1, width: 1.5, height: 1.5 },
      { type: 'box', x: 1, y: 1, width: 1.5, height: 1.5 },
    ],
    maxPathLength: 220,
    musicTrack: 'track2',
    backgroundColor: '#90EE90',
    difficulty: 'easy',
  },
  {
    name: 'Level 7',
    groupIndex: 1,
    ballStart: { x: 0, y: 4 },
    goalPosition: { x: 0, y: -4 },
    obstacles: [
      { type: 'box', x: -2, y: 2, width: 1, height: 1 },
      { type: 'box', x: 2, y: 0, width: 1, height: 1 },
      { type: 'box', x: -2, y: -2, width: 1, height: 1 },
    ],
    maxPathLength: 250,
    musicTrack: 'track2',
    backgroundColor: '#90EE90',
    difficulty: 'easy',
  },
  {
    name: 'Level 8',
    groupIndex: 1,
    ballStart: { x: -4, y: 3 },
    goalPosition: { x: 4, y: -3 },
    obstacles: [
      { type: 'box', x: -2, y: 1, width: 1.2, height: 1.2 },
      { type: 'box', x: 0, y: 0, width: 1.2, height: 1.2 },
      { type: 'box', x: 2, y: -1, width: 1.2, height: 1.2 },
    ],
    maxPathLength: 280,
    musicTrack: 'track2',
    backgroundColor: '#90EE90',
    difficulty: 'easy',
  },

  // Medium Group (8-14)
  {
    name: 'Level 9',
    groupIndex: 2,
    ballStart: { x: -4, y: 4 },
    goalPosition: { x: 4, y: -4 },
    obstacles: [
      { type: 'box', x: -2, y: 2, width: 1, height: 1 },
      { type: 'box', x: 0, y: 0, width: 2, height: 2 },
      { type: 'box', x: 2, y: -2, width: 1, height: 1 },
    ],
    maxPathLength: 300,
    musicTrack: 'track3',
    backgroundColor: '#FFB6C1',
    difficulty: 'medium',
  },
  {
    name: 'Level 10',
    groupIndex: 2,
    ballStart: { x: -3, y: 0 },
    goalPosition: { x: 3, y: 0 },
    obstacles: [
      { type: 'box', x: -1.5, y: 1.5, width: 1, height: 1 },
      { type: 'box', x: -1.5, y: -1.5, width: 1, height: 1 },
      { type: 'box', x: 1.5, y: 1.5, width: 1, height: 1 },
      { type: 'box', x: 1.5, y: -1.5, width: 1, height: 1 },
    ],
    maxPathLength: 320,
    musicTrack: 'track3',
    backgroundColor: '#FFB6C1',
    difficulty: 'medium',
  },
  {
    name: 'Level 11',
    groupIndex: 2,
    ballStart: { x: 0, y: 4 },
    goalPosition: { x: 0, y: -4 },
    obstacles: [
      { type: 'box', x: -2, y: 3, width: 1.5, height: 0.5 },
      { type: 'box', x: 2, y: 1, width: 1.5, height: 0.5 },
      { type: 'box', x: -2, y: -1, width: 1.5, height: 0.5 },
      { type: 'box', x: 2, y: -3, width: 1.5, height: 0.5 },
    ],
    maxPathLength: 350,
    musicTrack: 'track3',
    backgroundColor: '#FFB6C1',
    difficulty: 'medium',
  },
  {
    name: 'Level 12',
    groupIndex: 2,
    ballStart: { x: -4, y: 2 },
    goalPosition: { x: 4, y: 2 },
    obstacles: [
      { type: 'box', x: -2, y: 0, width: 0.8, height: 3 },
      { type: 'box', x: 0, y: 2, width: 3, height: 0.8 },
      { type: 'box', x: 2, y: 0, width: 0.8, height: 3 },
    ],
    maxPathLength: 400,
    musicTrack: 'track3',
    backgroundColor: '#FFB6C1',
    difficulty: 'medium',
  },
  {
    name: 'Level 13',
    groupIndex: 2,
    ballStart: { x: -3, y: -3 },
    goalPosition: { x: 3, y: 3 },
    obstacles: [
      { type: 'box', x: -2, y: 0, width: 1, height: 4 },
      { type: 'box', x: 2, y: 0, width: 1, height: 4 },
      { type: 'box', x: 0, y: 2, width: 2, height: 1 },
    ],
    maxPathLength: 420,
    musicTrack: 'track3',
    backgroundColor: '#FFB6C1',
    difficulty: 'medium',
  },
  {
    name: 'Level 14',
    groupIndex: 2,
    ballStart: { x: 0, y: 4 },
    goalPosition: { x: 0, y: -4 },
    obstacles: [
      { type: 'box', x: -1.5, y: 2.5, width: 1, height: 1 },
      { type: 'box', x: 1.5, y: 1.5, width: 1, height: 1 },
      { type: 'box', x: -1.5, y: 0.5, width: 1, height: 1 },
      { type: 'box', x: 1.5, y: -0.5, width: 1, height: 1 },
      { type: 'box', x: -1.5, y: -1.5, width: 1, height: 1 },
      { type: 'box', x: 1.5, y: -2.5, width: 1, height: 1 },
    ],
    maxPathLength: 450,
    musicTrack: 'track3',
    backgroundColor: '#FFB6C1',
    difficulty: 'medium',
  },
  {
    name: 'Level 15',
    groupIndex: 2,
    ballStart: { x: -4, y: 0 },
    goalPosition: { x: 4, y: 0 },
    obstacles: [
      { type: 'box', x: -2, y: 2, width: 1.5, height: 1.5 },
      { type: 'box', x: -2, y: -2, width: 1.5, height: 1.5 },
      { type: 'box', x: 0, y: 0, width: 1, height: 1 },
      { type: 'box', x: 2, y: 2, width: 1.5, height: 1.5 },
      { type: 'box', x: 2, y: -2, width: 1.5, height: 1.5 },
    ],
    maxPathLength: 500,
    musicTrack: 'track3',
    backgroundColor: '#FFB6C1',
    difficulty: 'medium',
  },

  // Hard Group (15-19)
  {
    name: 'Level 16',
    groupIndex: 3,
    ballStart: { x: -4, y: 4 },
    goalPosition: { x: 4, y: -4 },
    obstacles: [
      { type: 'box', x: -3, y: 2, width: 1, height: 1 },
      { type: 'box', x: -2, y: 0, width: 1, height: 1 },
      { type: 'box', x: -1, y: -2, width: 1, height: 1 },
      { type: 'box', x: 1, y: 2, width: 1, height: 1 },
      { type: 'box', x: 2, y: 0, width: 1, height: 1 },
      { type: 'box', x: 3, y: -2, width: 1, height: 1 },
    ],
    maxPathLength: 550,
    musicTrack: 'track3',
    backgroundColor: '#FFE4B5',
    difficulty: 'hard',
  },
  {
    name: 'Level 17',
    groupIndex: 3,
    ballStart: { x: 0, y: 4 },
    goalPosition: { x: 0, y: -4 },
    obstacles: [
      { type: 'box', x: -3, y: 3, width: 1.2, height: 1.2 },
      { type: 'box', x: 3, y: 3, width: 1.2, height: 1.2 },
      { type: 'box', x: -2, y: 1, width: 1.2, height: 1.2 },
      { type: 'box', x: 2, y: 1, width: 1.2, height: 1.2 },
      { type: 'box', x: -3, y: -1, width: 1.2, height: 1.2 },
      { type: 'box', x: 3, y: -1, width: 1.2, height: 1.2 },
      { type: 'box', x: 0, y: -3, width: 2, height: 1 },
    ],
    maxPathLength: 600,
    musicTrack: 'track3',
    backgroundColor: '#FFE4B5',
    difficulty: 'hard',
  },
  {
    name: 'Level 18',
    groupIndex: 3,
    ballStart: { x: -4, y: 0 },
    goalPosition: { x: 4, y: 0 },
    obstacles: [
      { type: 'box', x: -3, y: 2, width: 1, height: 1 },
      { type: 'box', x: -3, y: -2, width: 1, height: 1 },
      { type: 'box', x: -1, y: 1, width: 1, height: 1 },
      { type: 'box', x: -1, y: -1, width: 1, height: 1 },
      { type: 'box', x: 1, y: 1, width: 1, height: 1 },
      { type: 'box', x: 1, y: -1, width: 1, height: 1 },
      { type: 'box', x: 3, y: 2, width: 1, height: 1 },
      { type: 'box', x: 3, y: -2, width: 1, height: 1 },
    ],
    maxPathLength: 650,
    musicTrack: 'track3',
    backgroundColor: '#FFE4B5',
    difficulty: 'hard',
  },
  {
    name: 'Level 19',
    groupIndex: 3,
    ballStart: { x: -4, y: 3 },
    goalPosition: { x: 4, y: -3 },
    obstacles: [
      { type: 'box', x: -2.5, y: 2, width: 1, height: 1 },
      { type: 'box', x: -1.5, y: 0, width: 1, height: 1 },
      { type: 'box', x: -0.5, y: -2, width: 1, height: 1 },
      { type: 'box', x: 0.5, y: 2, width: 1, height: 1 },
      { type: 'box', x: 1.5, y: 0, width: 1, height: 1 },
      { type: 'box', x: 2.5, y: -2, width: 1, height: 1 },
      { type: 'box', x: 0, y: 1, width: 0.8, height: 0.8 },
      { type: 'box', x: 0, y: -1, width: 0.8, height: 0.8 },
    ],
    maxPathLength: 700,
    musicTrack: 'track3',
    backgroundColor: '#FFE4B5',
    difficulty: 'hard',
  },
  {
    name: 'Level 20',
    groupIndex: 3,
    ballStart: { x: 0, y: 4 },
    goalPosition: { x: 0, y: -4 },
    obstacles: [
      { type: 'box', x: -3, y: 3, width: 1, height: 1 },
      { type: 'box', x: 3, y: 3, width: 1, height: 1 },
      { type: 'box', x: -2, y: 1.5, width: 1, height: 1 },
      { type: 'box', x: 2, y: 1.5, width: 1, height: 1 },
      { type: 'box', x: -1, y: 0, width: 1, height: 1 },
      { type: 'box', x: 1, y: 0, width: 1, height: 1 },
      { type: 'box', x: -2, y: -1.5, width: 1, height: 1 },
      { type: 'box', x: 2, y: -1.5, width: 1, height: 1 },
      { type: 'box', x: -3, y: -3, width: 1, height: 1 },
      { type: 'box', x: 3, y: -3, width: 1, height: 1 },
    ],
    maxPathLength: 800,
    musicTrack: 'track3',
    backgroundColor: '#FFE4B5',
    difficulty: 'hard',
  },
];

export const PHYSICS_CONFIG = {
  gravity: { x: 0, y: -9.81, z: 0 },
  ballRadius: 0.25,
  ballMass: 1,
  pathFriction: 0.3,
  pathRestitution: 0.1,
};

export const GAME_CONFIG = {
  cameraFov: 60,
  cameraPosition: { x: 0, y: 0, z: 15 },
  pathColor: 0x00ffff,
  pathWidth: 0.3,
  ballColor: 0xff4444,
  goalColor: 0x44ff44,
  obstacleColor: 0x888888,
};
